env: 'local' # local/prod

github:
  access_token: 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
  owner: kurochkinivan
  repo: drone-config-history

http:
  host: 0.0.0.0
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  bytes_limit: 1024